# This defines a pipeline to build on Windows, Linux, and macOS in Debug mode.

pr:
  batch: true
  branches:
    include:
    - contrib

stages:
  - stage: build
    displayName: Build
    jobs:
    - template: jobs.yml
      parameters:
        debug: true
        name: Windows
    - template: jobs.yml
      parameters:
        debug: true
        name: Linux
    - template: jobs.yml
      parameters:
        debug: true
        name: macOS